// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package everythinglocationapi.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ShortenList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> List;
	private java.lang.Long Length;

	public ShortenList(IContext context, java.util.List<IMendixObject> List, java.lang.Long Length)
	{
		super(context);
		this.List = List;
		this.Length = Length;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> returnList = new ArrayList<>();
		
		for (int x = 0; x < this.Length; x++) {
			if (this.List.size() >= (x + 1))
				returnList.add(this.List.get(x));
			else
				break;
		}
		return returnList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShortenList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
