// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_Address_Select(IContext context, postcodelookup.proxies.FindResult _selectedFindResult, postcodelookup.proxies.Search _search, myfirstmodule.proxies.Address _address)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SelectedFindResult", _selectedFindResult == null ? null : _selectedFindResult.getMendixObject());
			params.put("Search", _search == null ? null : _search.getMendixObject());
			params.put("Address", _address == null ? null : _address.getMendixObject());
			Core.execute(context, "MyFirstModule.ACT_Address_Select", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static myfirstmodule.proxies.Address dS_Address(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.DS_Address", params);
			return result == null ? null : myfirstmodule.proxies.Address.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}