// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postcodelookup.proxies;

public enum Enum_SearchStatus
{
	Searching(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Searching" } }),
	No_results(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "No results" } }),
	Success(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Success" } }),
	Error(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Error" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_SearchStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_GB");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_GB");
	}
}
