// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postcodelookup.proxies;

public class FindResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject findResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostcodeLookup.FindResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Id("_Id"),
		_Type("_Type"),
		Text("Text"),
		Highlight("Highlight"),
		Description("Description"),
		FindResult_RetrieveResult("PostcodeLookup.FindResult_RetrieveResult"),
		FindResult_Search("PostcodeLookup.FindResult_Search");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FindResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostcodeLookup.FindResult"));
	}

	protected FindResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject findResultMendixObject)
	{
		if (findResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostcodeLookup.FindResult", findResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostcodeLookup.FindResult");

		this.findResultMendixObject = findResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FindResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static postcodelookup.proxies.FindResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postcodelookup.proxies.FindResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postcodelookup.proxies.FindResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postcodelookup.proxies.FindResult(context, mendixObject);
	}

	public static postcodelookup.proxies.FindResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postcodelookup.proxies.FindResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Id
	 */
	public final java.lang.String get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.String get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.String _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of _Type
	 */
	public final java.lang.String get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final java.lang.String get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Type.toString());
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(java.lang.String _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._Type.toString(), _type);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Highlight
	 */
	public final java.lang.String getHighlight()
	{
		return getHighlight(getContext());
	}

	/**
	 * @param context
	 * @return value of Highlight
	 */
	public final java.lang.String getHighlight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Highlight.toString());
	}

	/**
	 * Set value of Highlight
	 * @param highlight
	 */
	public final void setHighlight(java.lang.String highlight)
	{
		setHighlight(getContext(), highlight);
	}

	/**
	 * Set value of Highlight
	 * @param context
	 * @param highlight
	 */
	public final void setHighlight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String highlight)
	{
		getMendixObject().setValue(context, MemberNames.Highlight.toString(), highlight);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of FindResult_RetrieveResult
	 */
	public final postcodelookup.proxies.RetrieveResult getFindResult_RetrieveResult() throws com.mendix.core.CoreException
	{
		return getFindResult_RetrieveResult(getContext());
	}

	/**
	 * @param context
	 * @return value of FindResult_RetrieveResult
	 */
	public final postcodelookup.proxies.RetrieveResult getFindResult_RetrieveResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postcodelookup.proxies.RetrieveResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FindResult_RetrieveResult.toString());
		if (identifier != null)
			result = postcodelookup.proxies.RetrieveResult.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FindResult_RetrieveResult
	 * @param findresult_retrieveresult
	 */
	public final void setFindResult_RetrieveResult(postcodelookup.proxies.RetrieveResult findresult_retrieveresult)
	{
		setFindResult_RetrieveResult(getContext(), findresult_retrieveresult);
	}

	/**
	 * Set value of FindResult_RetrieveResult
	 * @param context
	 * @param findresult_retrieveresult
	 */
	public final void setFindResult_RetrieveResult(com.mendix.systemwideinterfaces.core.IContext context, postcodelookup.proxies.RetrieveResult findresult_retrieveresult)
	{
		if (findresult_retrieveresult == null)
			getMendixObject().setValue(context, MemberNames.FindResult_RetrieveResult.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FindResult_RetrieveResult.toString(), findresult_retrieveresult.getMendixObject().getId());
	}

	/**
	 * @return value of FindResult_Search
	 */
	public final postcodelookup.proxies.Search getFindResult_Search() throws com.mendix.core.CoreException
	{
		return getFindResult_Search(getContext());
	}

	/**
	 * @param context
	 * @return value of FindResult_Search
	 */
	public final postcodelookup.proxies.Search getFindResult_Search(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postcodelookup.proxies.Search result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FindResult_Search.toString());
		if (identifier != null)
			result = postcodelookup.proxies.Search.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FindResult_Search
	 * @param findresult_search
	 */
	public final void setFindResult_Search(postcodelookup.proxies.Search findresult_search)
	{
		setFindResult_Search(getContext(), findresult_search);
	}

	/**
	 * Set value of FindResult_Search
	 * @param context
	 * @param findresult_search
	 */
	public final void setFindResult_Search(com.mendix.systemwideinterfaces.core.IContext context, postcodelookup.proxies.Search findresult_search)
	{
		if (findresult_search == null)
			getMendixObject().setValue(context, MemberNames.FindResult_Search.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FindResult_Search.toString(), findresult_search.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return findResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postcodelookup.proxies.FindResult that = (postcodelookup.proxies.FindResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostcodeLookup.FindResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
