// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postcodelookup.proxies;

public class RetrieveResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retrieveResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostcodeLookup.RetrieveResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LastUpdated("LastUpdated"),
		_Id("_Id"),
		_Type("_Type"),
		DomesticId("DomesticId"),
		Language("Language"),
		LanguageAlternatives("LanguageAlternatives"),
		Department("Department"),
		Company("Company"),
		SubBuilding("SubBuilding"),
		BuildingNumber("BuildingNumber"),
		BuildingName("BuildingName"),
		SecondaryStreet("SecondaryStreet"),
		Street("Street"),
		Block("Block"),
		Neighbourhood("Neighbourhood"),
		District("District"),
		City("City"),
		Line1("Line1"),
		Line2("Line2"),
		Line3("Line3"),
		Line4("Line4"),
		Line5("Line5"),
		AdminAreaName("AdminAreaName"),
		AdminAreaCode("AdminAreaCode"),
		Province("Province"),
		ProvinceName("ProvinceName"),
		ProvinceCode("ProvinceCode"),
		PostalCode("PostalCode"),
		CountryName("CountryName"),
		CountryIso2("CountryIso2"),
		CountryIso3("CountryIso3"),
		CountryIsoNumber("CountryIsoNumber"),
		SortingNumber1("SortingNumber1"),
		SortingNumber2("SortingNumber2"),
		Barcode("Barcode"),
		POBoxNumber("POBoxNumber"),
		Label("Label"),
		DataLevel("DataLevel"),
		RetrieveResult_Country("PostcodeLookup.RetrieveResult_Country");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrieveResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostcodeLookup.RetrieveResult"));
	}

	protected RetrieveResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrieveResultMendixObject)
	{
		if (retrieveResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostcodeLookup.RetrieveResult", retrieveResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostcodeLookup.RetrieveResult");

		this.retrieveResultMendixObject = retrieveResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RetrieveResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static postcodelookup.proxies.RetrieveResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postcodelookup.proxies.RetrieveResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postcodelookup.proxies.RetrieveResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postcodelookup.proxies.RetrieveResult(context, mendixObject);
	}

	public static postcodelookup.proxies.RetrieveResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postcodelookup.proxies.RetrieveResult.initialize(context, mendixObject);
	}

	public static java.util.List<postcodelookup.proxies.RetrieveResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<postcodelookup.proxies.RetrieveResult> result = new java.util.ArrayList<postcodelookup.proxies.RetrieveResult>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PostcodeLookup.RetrieveResult" + xpathConstraint))
			result.add(postcodelookup.proxies.RetrieveResult.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LastUpdated
	 */
	public final java.util.Date getLastUpdated()
	{
		return getLastUpdated(getContext());
	}

	/**
	 * @param context
	 * @return value of LastUpdated
	 */
	public final java.util.Date getLastUpdated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastUpdated.toString());
	}

	/**
	 * Set value of LastUpdated
	 * @param lastupdated
	 */
	public final void setLastUpdated(java.util.Date lastupdated)
	{
		setLastUpdated(getContext(), lastupdated);
	}

	/**
	 * Set value of LastUpdated
	 * @param context
	 * @param lastupdated
	 */
	public final void setLastUpdated(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastupdated)
	{
		getMendixObject().setValue(context, MemberNames.LastUpdated.toString(), lastupdated);
	}

	/**
	 * @return value of _Id
	 */
	public final java.lang.String get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.String get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.String _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of _Type
	 */
	public final java.lang.String get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final java.lang.String get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Type.toString());
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(java.lang.String _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._Type.toString(), _type);
	}

	/**
	 * @return value of DomesticId
	 */
	public final java.lang.String getDomesticId()
	{
		return getDomesticId(getContext());
	}

	/**
	 * @param context
	 * @return value of DomesticId
	 */
	public final java.lang.String getDomesticId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DomesticId.toString());
	}

	/**
	 * Set value of DomesticId
	 * @param domesticid
	 */
	public final void setDomesticId(java.lang.String domesticid)
	{
		setDomesticId(getContext(), domesticid);
	}

	/**
	 * Set value of DomesticId
	 * @param context
	 * @param domesticid
	 */
	public final void setDomesticId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String domesticid)
	{
		getMendixObject().setValue(context, MemberNames.DomesticId.toString(), domesticid);
	}

	/**
	 * @return value of Language
	 */
	public final java.lang.String getLanguage()
	{
		return getLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of Language
	 */
	public final java.lang.String getLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Language.toString());
	}

	/**
	 * Set value of Language
	 * @param language
	 */
	public final void setLanguage(java.lang.String language)
	{
		setLanguage(getContext(), language);
	}

	/**
	 * Set value of Language
	 * @param context
	 * @param language
	 */
	public final void setLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String language)
	{
		getMendixObject().setValue(context, MemberNames.Language.toString(), language);
	}

	/**
	 * @return value of LanguageAlternatives
	 */
	public final java.lang.String getLanguageAlternatives()
	{
		return getLanguageAlternatives(getContext());
	}

	/**
	 * @param context
	 * @return value of LanguageAlternatives
	 */
	public final java.lang.String getLanguageAlternatives(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LanguageAlternatives.toString());
	}

	/**
	 * Set value of LanguageAlternatives
	 * @param languagealternatives
	 */
	public final void setLanguageAlternatives(java.lang.String languagealternatives)
	{
		setLanguageAlternatives(getContext(), languagealternatives);
	}

	/**
	 * Set value of LanguageAlternatives
	 * @param context
	 * @param languagealternatives
	 */
	public final void setLanguageAlternatives(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String languagealternatives)
	{
		getMendixObject().setValue(context, MemberNames.LanguageAlternatives.toString(), languagealternatives);
	}

	/**
	 * @return value of Department
	 */
	public final java.lang.String getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final java.lang.String getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Department.toString());
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(java.lang.String department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String department)
	{
		getMendixObject().setValue(context, MemberNames.Department.toString(), department);
	}

	/**
	 * @return value of Company
	 */
	public final java.lang.String getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final java.lang.String getCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(java.lang.String company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of SubBuilding
	 */
	public final java.lang.String getSubBuilding()
	{
		return getSubBuilding(getContext());
	}

	/**
	 * @param context
	 * @return value of SubBuilding
	 */
	public final java.lang.String getSubBuilding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubBuilding.toString());
	}

	/**
	 * Set value of SubBuilding
	 * @param subbuilding
	 */
	public final void setSubBuilding(java.lang.String subbuilding)
	{
		setSubBuilding(getContext(), subbuilding);
	}

	/**
	 * Set value of SubBuilding
	 * @param context
	 * @param subbuilding
	 */
	public final void setSubBuilding(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subbuilding)
	{
		getMendixObject().setValue(context, MemberNames.SubBuilding.toString(), subbuilding);
	}

	/**
	 * @return value of BuildingNumber
	 */
	public final java.lang.String getBuildingNumber()
	{
		return getBuildingNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of BuildingNumber
	 */
	public final java.lang.String getBuildingNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BuildingNumber.toString());
	}

	/**
	 * Set value of BuildingNumber
	 * @param buildingnumber
	 */
	public final void setBuildingNumber(java.lang.String buildingnumber)
	{
		setBuildingNumber(getContext(), buildingnumber);
	}

	/**
	 * Set value of BuildingNumber
	 * @param context
	 * @param buildingnumber
	 */
	public final void setBuildingNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String buildingnumber)
	{
		getMendixObject().setValue(context, MemberNames.BuildingNumber.toString(), buildingnumber);
	}

	/**
	 * @return value of BuildingName
	 */
	public final java.lang.String getBuildingName()
	{
		return getBuildingName(getContext());
	}

	/**
	 * @param context
	 * @return value of BuildingName
	 */
	public final java.lang.String getBuildingName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BuildingName.toString());
	}

	/**
	 * Set value of BuildingName
	 * @param buildingname
	 */
	public final void setBuildingName(java.lang.String buildingname)
	{
		setBuildingName(getContext(), buildingname);
	}

	/**
	 * Set value of BuildingName
	 * @param context
	 * @param buildingname
	 */
	public final void setBuildingName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String buildingname)
	{
		getMendixObject().setValue(context, MemberNames.BuildingName.toString(), buildingname);
	}

	/**
	 * @return value of SecondaryStreet
	 */
	public final java.lang.String getSecondaryStreet()
	{
		return getSecondaryStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of SecondaryStreet
	 */
	public final java.lang.String getSecondaryStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecondaryStreet.toString());
	}

	/**
	 * Set value of SecondaryStreet
	 * @param secondarystreet
	 */
	public final void setSecondaryStreet(java.lang.String secondarystreet)
	{
		setSecondaryStreet(getContext(), secondarystreet);
	}

	/**
	 * Set value of SecondaryStreet
	 * @param context
	 * @param secondarystreet
	 */
	public final void setSecondaryStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secondarystreet)
	{
		getMendixObject().setValue(context, MemberNames.SecondaryStreet.toString(), secondarystreet);
	}

	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of Block
	 */
	public final java.lang.String getBlock()
	{
		return getBlock(getContext());
	}

	/**
	 * @param context
	 * @return value of Block
	 */
	public final java.lang.String getBlock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Block.toString());
	}

	/**
	 * Set value of Block
	 * @param block
	 */
	public final void setBlock(java.lang.String block)
	{
		setBlock(getContext(), block);
	}

	/**
	 * Set value of Block
	 * @param context
	 * @param block
	 */
	public final void setBlock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String block)
	{
		getMendixObject().setValue(context, MemberNames.Block.toString(), block);
	}

	/**
	 * @return value of Neighbourhood
	 */
	public final java.lang.String getNeighbourhood()
	{
		return getNeighbourhood(getContext());
	}

	/**
	 * @param context
	 * @return value of Neighbourhood
	 */
	public final java.lang.String getNeighbourhood(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Neighbourhood.toString());
	}

	/**
	 * Set value of Neighbourhood
	 * @param neighbourhood
	 */
	public final void setNeighbourhood(java.lang.String neighbourhood)
	{
		setNeighbourhood(getContext(), neighbourhood);
	}

	/**
	 * Set value of Neighbourhood
	 * @param context
	 * @param neighbourhood
	 */
	public final void setNeighbourhood(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String neighbourhood)
	{
		getMendixObject().setValue(context, MemberNames.Neighbourhood.toString(), neighbourhood);
	}

	/**
	 * @return value of District
	 */
	public final java.lang.String getDistrict()
	{
		return getDistrict(getContext());
	}

	/**
	 * @param context
	 * @return value of District
	 */
	public final java.lang.String getDistrict(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.District.toString());
	}

	/**
	 * Set value of District
	 * @param district
	 */
	public final void setDistrict(java.lang.String district)
	{
		setDistrict(getContext(), district);
	}

	/**
	 * Set value of District
	 * @param context
	 * @param district
	 */
	public final void setDistrict(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String district)
	{
		getMendixObject().setValue(context, MemberNames.District.toString(), district);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Line1
	 */
	public final java.lang.String getLine1()
	{
		return getLine1(getContext());
	}

	/**
	 * @param context
	 * @return value of Line1
	 */
	public final java.lang.String getLine1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Line1.toString());
	}

	/**
	 * Set value of Line1
	 * @param line1
	 */
	public final void setLine1(java.lang.String line1)
	{
		setLine1(getContext(), line1);
	}

	/**
	 * Set value of Line1
	 * @param context
	 * @param line1
	 */
	public final void setLine1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String line1)
	{
		getMendixObject().setValue(context, MemberNames.Line1.toString(), line1);
	}

	/**
	 * @return value of Line2
	 */
	public final java.lang.String getLine2()
	{
		return getLine2(getContext());
	}

	/**
	 * @param context
	 * @return value of Line2
	 */
	public final java.lang.String getLine2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Line2.toString());
	}

	/**
	 * Set value of Line2
	 * @param line2
	 */
	public final void setLine2(java.lang.String line2)
	{
		setLine2(getContext(), line2);
	}

	/**
	 * Set value of Line2
	 * @param context
	 * @param line2
	 */
	public final void setLine2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String line2)
	{
		getMendixObject().setValue(context, MemberNames.Line2.toString(), line2);
	}

	/**
	 * @return value of Line3
	 */
	public final java.lang.String getLine3()
	{
		return getLine3(getContext());
	}

	/**
	 * @param context
	 * @return value of Line3
	 */
	public final java.lang.String getLine3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Line3.toString());
	}

	/**
	 * Set value of Line3
	 * @param line3
	 */
	public final void setLine3(java.lang.String line3)
	{
		setLine3(getContext(), line3);
	}

	/**
	 * Set value of Line3
	 * @param context
	 * @param line3
	 */
	public final void setLine3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String line3)
	{
		getMendixObject().setValue(context, MemberNames.Line3.toString(), line3);
	}

	/**
	 * @return value of Line4
	 */
	public final java.lang.String getLine4()
	{
		return getLine4(getContext());
	}

	/**
	 * @param context
	 * @return value of Line4
	 */
	public final java.lang.String getLine4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Line4.toString());
	}

	/**
	 * Set value of Line4
	 * @param line4
	 */
	public final void setLine4(java.lang.String line4)
	{
		setLine4(getContext(), line4);
	}

	/**
	 * Set value of Line4
	 * @param context
	 * @param line4
	 */
	public final void setLine4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String line4)
	{
		getMendixObject().setValue(context, MemberNames.Line4.toString(), line4);
	}

	/**
	 * @return value of Line5
	 */
	public final java.lang.String getLine5()
	{
		return getLine5(getContext());
	}

	/**
	 * @param context
	 * @return value of Line5
	 */
	public final java.lang.String getLine5(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Line5.toString());
	}

	/**
	 * Set value of Line5
	 * @param line5
	 */
	public final void setLine5(java.lang.String line5)
	{
		setLine5(getContext(), line5);
	}

	/**
	 * Set value of Line5
	 * @param context
	 * @param line5
	 */
	public final void setLine5(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String line5)
	{
		getMendixObject().setValue(context, MemberNames.Line5.toString(), line5);
	}

	/**
	 * @return value of AdminAreaName
	 */
	public final java.lang.String getAdminAreaName()
	{
		return getAdminAreaName(getContext());
	}

	/**
	 * @param context
	 * @return value of AdminAreaName
	 */
	public final java.lang.String getAdminAreaName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdminAreaName.toString());
	}

	/**
	 * Set value of AdminAreaName
	 * @param adminareaname
	 */
	public final void setAdminAreaName(java.lang.String adminareaname)
	{
		setAdminAreaName(getContext(), adminareaname);
	}

	/**
	 * Set value of AdminAreaName
	 * @param context
	 * @param adminareaname
	 */
	public final void setAdminAreaName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adminareaname)
	{
		getMendixObject().setValue(context, MemberNames.AdminAreaName.toString(), adminareaname);
	}

	/**
	 * @return value of AdminAreaCode
	 */
	public final java.lang.String getAdminAreaCode()
	{
		return getAdminAreaCode(getContext());
	}

	/**
	 * @param context
	 * @return value of AdminAreaCode
	 */
	public final java.lang.String getAdminAreaCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdminAreaCode.toString());
	}

	/**
	 * Set value of AdminAreaCode
	 * @param adminareacode
	 */
	public final void setAdminAreaCode(java.lang.String adminareacode)
	{
		setAdminAreaCode(getContext(), adminareacode);
	}

	/**
	 * Set value of AdminAreaCode
	 * @param context
	 * @param adminareacode
	 */
	public final void setAdminAreaCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adminareacode)
	{
		getMendixObject().setValue(context, MemberNames.AdminAreaCode.toString(), adminareacode);
	}

	/**
	 * @return value of Province
	 */
	public final java.lang.String getProvince()
	{
		return getProvince(getContext());
	}

	/**
	 * @param context
	 * @return value of Province
	 */
	public final java.lang.String getProvince(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Province.toString());
	}

	/**
	 * Set value of Province
	 * @param province
	 */
	public final void setProvince(java.lang.String province)
	{
		setProvince(getContext(), province);
	}

	/**
	 * Set value of Province
	 * @param context
	 * @param province
	 */
	public final void setProvince(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String province)
	{
		getMendixObject().setValue(context, MemberNames.Province.toString(), province);
	}

	/**
	 * @return value of ProvinceName
	 */
	public final java.lang.String getProvinceName()
	{
		return getProvinceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProvinceName
	 */
	public final java.lang.String getProvinceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProvinceName.toString());
	}

	/**
	 * Set value of ProvinceName
	 * @param provincename
	 */
	public final void setProvinceName(java.lang.String provincename)
	{
		setProvinceName(getContext(), provincename);
	}

	/**
	 * Set value of ProvinceName
	 * @param context
	 * @param provincename
	 */
	public final void setProvinceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String provincename)
	{
		getMendixObject().setValue(context, MemberNames.ProvinceName.toString(), provincename);
	}

	/**
	 * @return value of ProvinceCode
	 */
	public final java.lang.String getProvinceCode()
	{
		return getProvinceCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProvinceCode
	 */
	public final java.lang.String getProvinceCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProvinceCode.toString());
	}

	/**
	 * Set value of ProvinceCode
	 * @param provincecode
	 */
	public final void setProvinceCode(java.lang.String provincecode)
	{
		setProvinceCode(getContext(), provincecode);
	}

	/**
	 * Set value of ProvinceCode
	 * @param context
	 * @param provincecode
	 */
	public final void setProvinceCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String provincecode)
	{
		getMendixObject().setValue(context, MemberNames.ProvinceCode.toString(), provincecode);
	}

	/**
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode()
	{
		return getPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostalCode.toString());
	}

	/**
	 * Set value of PostalCode
	 * @param postalcode
	 */
	public final void setPostalCode(java.lang.String postalcode)
	{
		setPostalCode(getContext(), postalcode);
	}

	/**
	 * Set value of PostalCode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.PostalCode.toString(), postalcode);
	}

	/**
	 * @return value of CountryName
	 */
	public final java.lang.String getCountryName()
	{
		return getCountryName(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryName
	 */
	public final java.lang.String getCountryName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryName.toString());
	}

	/**
	 * Set value of CountryName
	 * @param countryname
	 */
	public final void setCountryName(java.lang.String countryname)
	{
		setCountryName(getContext(), countryname);
	}

	/**
	 * Set value of CountryName
	 * @param context
	 * @param countryname
	 */
	public final void setCountryName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countryname)
	{
		getMendixObject().setValue(context, MemberNames.CountryName.toString(), countryname);
	}

	/**
	 * @return value of CountryIso2
	 */
	public final java.lang.String getCountryIso2()
	{
		return getCountryIso2(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryIso2
	 */
	public final java.lang.String getCountryIso2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryIso2.toString());
	}

	/**
	 * Set value of CountryIso2
	 * @param countryiso2
	 */
	public final void setCountryIso2(java.lang.String countryiso2)
	{
		setCountryIso2(getContext(), countryiso2);
	}

	/**
	 * Set value of CountryIso2
	 * @param context
	 * @param countryiso2
	 */
	public final void setCountryIso2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countryiso2)
	{
		getMendixObject().setValue(context, MemberNames.CountryIso2.toString(), countryiso2);
	}

	/**
	 * @return value of CountryIso3
	 */
	public final java.lang.String getCountryIso3()
	{
		return getCountryIso3(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryIso3
	 */
	public final java.lang.String getCountryIso3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryIso3.toString());
	}

	/**
	 * Set value of CountryIso3
	 * @param countryiso3
	 */
	public final void setCountryIso3(java.lang.String countryiso3)
	{
		setCountryIso3(getContext(), countryiso3);
	}

	/**
	 * Set value of CountryIso3
	 * @param context
	 * @param countryiso3
	 */
	public final void setCountryIso3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countryiso3)
	{
		getMendixObject().setValue(context, MemberNames.CountryIso3.toString(), countryiso3);
	}

	/**
	 * @return value of CountryIsoNumber
	 */
	public final java.lang.Integer getCountryIsoNumber()
	{
		return getCountryIsoNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryIsoNumber
	 */
	public final java.lang.Integer getCountryIsoNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountryIsoNumber.toString());
	}

	/**
	 * Set value of CountryIsoNumber
	 * @param countryisonumber
	 */
	public final void setCountryIsoNumber(java.lang.Integer countryisonumber)
	{
		setCountryIsoNumber(getContext(), countryisonumber);
	}

	/**
	 * Set value of CountryIsoNumber
	 * @param context
	 * @param countryisonumber
	 */
	public final void setCountryIsoNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countryisonumber)
	{
		getMendixObject().setValue(context, MemberNames.CountryIsoNumber.toString(), countryisonumber);
	}

	/**
	 * @return value of SortingNumber1
	 */
	public final java.lang.String getSortingNumber1()
	{
		return getSortingNumber1(getContext());
	}

	/**
	 * @param context
	 * @return value of SortingNumber1
	 */
	public final java.lang.String getSortingNumber1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SortingNumber1.toString());
	}

	/**
	 * Set value of SortingNumber1
	 * @param sortingnumber1
	 */
	public final void setSortingNumber1(java.lang.String sortingnumber1)
	{
		setSortingNumber1(getContext(), sortingnumber1);
	}

	/**
	 * Set value of SortingNumber1
	 * @param context
	 * @param sortingnumber1
	 */
	public final void setSortingNumber1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sortingnumber1)
	{
		getMendixObject().setValue(context, MemberNames.SortingNumber1.toString(), sortingnumber1);
	}

	/**
	 * @return value of SortingNumber2
	 */
	public final java.lang.String getSortingNumber2()
	{
		return getSortingNumber2(getContext());
	}

	/**
	 * @param context
	 * @return value of SortingNumber2
	 */
	public final java.lang.String getSortingNumber2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SortingNumber2.toString());
	}

	/**
	 * Set value of SortingNumber2
	 * @param sortingnumber2
	 */
	public final void setSortingNumber2(java.lang.String sortingnumber2)
	{
		setSortingNumber2(getContext(), sortingnumber2);
	}

	/**
	 * Set value of SortingNumber2
	 * @param context
	 * @param sortingnumber2
	 */
	public final void setSortingNumber2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sortingnumber2)
	{
		getMendixObject().setValue(context, MemberNames.SortingNumber2.toString(), sortingnumber2);
	}

	/**
	 * @return value of Barcode
	 */
	public final java.lang.String getBarcode()
	{
		return getBarcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Barcode
	 */
	public final java.lang.String getBarcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Barcode.toString());
	}

	/**
	 * Set value of Barcode
	 * @param barcode
	 */
	public final void setBarcode(java.lang.String barcode)
	{
		setBarcode(getContext(), barcode);
	}

	/**
	 * Set value of Barcode
	 * @param context
	 * @param barcode
	 */
	public final void setBarcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String barcode)
	{
		getMendixObject().setValue(context, MemberNames.Barcode.toString(), barcode);
	}

	/**
	 * @return value of POBoxNumber
	 */
	public final java.lang.String getPOBoxNumber()
	{
		return getPOBoxNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of POBoxNumber
	 */
	public final java.lang.String getPOBoxNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.POBoxNumber.toString());
	}

	/**
	 * Set value of POBoxNumber
	 * @param poboxnumber
	 */
	public final void setPOBoxNumber(java.lang.String poboxnumber)
	{
		setPOBoxNumber(getContext(), poboxnumber);
	}

	/**
	 * Set value of POBoxNumber
	 * @param context
	 * @param poboxnumber
	 */
	public final void setPOBoxNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String poboxnumber)
	{
		getMendixObject().setValue(context, MemberNames.POBoxNumber.toString(), poboxnumber);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of DataLevel
	 */
	public final java.lang.String getDataLevel()
	{
		return getDataLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of DataLevel
	 */
	public final java.lang.String getDataLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataLevel.toString());
	}

	/**
	 * Set value of DataLevel
	 * @param datalevel
	 */
	public final void setDataLevel(java.lang.String datalevel)
	{
		setDataLevel(getContext(), datalevel);
	}

	/**
	 * Set value of DataLevel
	 * @param context
	 * @param datalevel
	 */
	public final void setDataLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datalevel)
	{
		getMendixObject().setValue(context, MemberNames.DataLevel.toString(), datalevel);
	}

	/**
	 * @return value of RetrieveResult_Country
	 */
	public final postcodelookup.proxies.Country getRetrieveResult_Country() throws com.mendix.core.CoreException
	{
		return getRetrieveResult_Country(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveResult_Country
	 */
	public final postcodelookup.proxies.Country getRetrieveResult_Country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postcodelookup.proxies.Country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveResult_Country.toString());
		if (identifier != null)
			result = postcodelookup.proxies.Country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RetrieveResult_Country
	 * @param retrieveresult_country
	 */
	public final void setRetrieveResult_Country(postcodelookup.proxies.Country retrieveresult_country)
	{
		setRetrieveResult_Country(getContext(), retrieveresult_country);
	}

	/**
	 * Set value of RetrieveResult_Country
	 * @param context
	 * @param retrieveresult_country
	 */
	public final void setRetrieveResult_Country(com.mendix.systemwideinterfaces.core.IContext context, postcodelookup.proxies.Country retrieveresult_country)
	{
		if (retrieveresult_country == null)
			getMendixObject().setValue(context, MemberNames.RetrieveResult_Country.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RetrieveResult_Country.toString(), retrieveresult_country.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retrieveResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postcodelookup.proxies.RetrieveResult that = (postcodelookup.proxies.RetrieveResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostcodeLookup.RetrieveResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
