// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package loqatepostcodelookup.proxies;

public class Search
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "LoqatePostcodeLookup.Search";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SearchText("SearchText"),
		SearchContainer("SearchContainer"),
		Search_Country("LoqatePostcodeLookup.Search_Country");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Search(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "LoqatePostcodeLookup.Search"));
	}

	protected Search(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject)
	{
		if (searchMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("LoqatePostcodeLookup.Search", searchMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a LoqatePostcodeLookup.Search");

		this.searchMendixObject = searchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Search.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static loqatepostcodelookup.proxies.Search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return loqatepostcodelookup.proxies.Search.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static loqatepostcodelookup.proxies.Search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new loqatepostcodelookup.proxies.Search(context, mendixObject);
	}

	public static loqatepostcodelookup.proxies.Search load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return loqatepostcodelookup.proxies.Search.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SearchText
	 */
	public final java.lang.String getSearchText()
	{
		return getSearchText(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchText
	 */
	public final java.lang.String getSearchText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchText.toString());
	}

	/**
	 * Set value of SearchText
	 * @param searchtext
	 */
	public final void setSearchText(java.lang.String searchtext)
	{
		setSearchText(getContext(), searchtext);
	}

	/**
	 * Set value of SearchText
	 * @param context
	 * @param searchtext
	 */
	public final void setSearchText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchtext)
	{
		getMendixObject().setValue(context, MemberNames.SearchText.toString(), searchtext);
	}

	/**
	 * @return value of SearchContainer
	 */
	public final java.lang.String getSearchContainer()
	{
		return getSearchContainer(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchContainer
	 */
	public final java.lang.String getSearchContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchContainer.toString());
	}

	/**
	 * Set value of SearchContainer
	 * @param searchcontainer
	 */
	public final void setSearchContainer(java.lang.String searchcontainer)
	{
		setSearchContainer(getContext(), searchcontainer);
	}

	/**
	 * Set value of SearchContainer
	 * @param context
	 * @param searchcontainer
	 */
	public final void setSearchContainer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchcontainer)
	{
		getMendixObject().setValue(context, MemberNames.SearchContainer.toString(), searchcontainer);
	}

	/**
	 * @return value of Search_Country
	 */
	public final loqatepostcodelookup.proxies.Country getSearch_Country() throws com.mendix.core.CoreException
	{
		return getSearch_Country(getContext());
	}

	/**
	 * @param context
	 * @return value of Search_Country
	 */
	public final loqatepostcodelookup.proxies.Country getSearch_Country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		loqatepostcodelookup.proxies.Country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Search_Country.toString());
		if (identifier != null)
			result = loqatepostcodelookup.proxies.Country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Search_Country
	 * @param search_country
	 */
	public final void setSearch_Country(loqatepostcodelookup.proxies.Country search_country)
	{
		setSearch_Country(getContext(), search_country);
	}

	/**
	 * Set value of Search_Country
	 * @param context
	 * @param search_country
	 */
	public final void setSearch_Country(com.mendix.systemwideinterfaces.core.IContext context, loqatepostcodelookup.proxies.Country search_country)
	{
		if (search_country == null)
			getMendixObject().setValue(context, MemberNames.Search_Country.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Search_Country.toString(), search_country.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final loqatepostcodelookup.proxies.Search that = (loqatepostcodelookup.proxies.Search) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "LoqatePostcodeLookup.Search";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
